etcd:
  endpoints:
    - "127.0.0.1:2379"
    - "127.0.0.2:2379"
caPath:
  cert: "/etc/kubernetes/pki/etcd/peer.crt"
  key: "/etc/kubernetes/pki/etcd/peer.key"
  cacert: "/etc/kubernetes/pki/etcd/ca.crt"
backupLocation: "/tmp/backup"
s3BucketName: "etcd-backup"
s3Endpoint: "minio-cluster.cluster.morteza.dev"
s3Region: "eu-central"
s3AccessKey: "accesskey"
s3SecretKey: "secretkey"
